flows:
  default:
  - log: "Hello Concord User"
  onPush:
  - log: "${event.sender} pushed ${event.commitId} to ${event.payload.repository.full_name}"  
  
  
triggers:
- github:
    useInitiator: true
    entryPoint: onPush
    conditions:
      type: push  

- github:
    entryPoint: "onPush"
    conditions:
      type: "push"
